language: python
python:
  - "3.7"
  - "2.7"
install:
  - pip install .
before_script:
  - pip install pycodestyle pytest-cov coveralls
script:
  - pycodestyle factorgraph/ tests/
  - py.test --cov=factorgraph tests/
after_success:
  - coveralls

